title: Classifying Healthcare Procurement Data Using Machine Learning
description: Kelli Fletcher - AOS C204, Fall 2024
logo: /assets/IMG/ML class final proj logo.png
show_downloads: true
future: true

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
