title: Classifying Healthcare Procurement Data Using Machine Learning
description: Kelli Fletcher - AOS C204, Fall 2024
logo: /assets/IMG/ML class final proj logo.png
show_downloads: true
theme: jekyll-theme-midnight 
